from setuptools import setup
def readme():
    with open('README.rst') as f:
        return f.read()
setup(name='Mypackage',
      version='0.1.0',
      description='The random numbers generated by distributions',
      long_description='Generation, random numbers, using distributions.',
      classifiers=[
        'Development Status :: 3 - Alpha',
        'License :: SiMLeng License',
        'Programming Language :: Python :: 3.8',
        'Topic :: OOP Python :: Code',
      ],
      url='http://github.com/sednabcn/Python-Package-Explained',
      entry_points = {
        'console_scripts': ['mypackage-sample=mypackage.command_line:mypackage_results'],
      },
      author='sedna',
      author_email='sednalondon@gmail.com',
      license='SiMLeng',
      packages=['mypackage','mypackage.subpackage','mypackage.tests'],
      install_requires=[
          'numpy',],
      test_suite='nose.collector',
      tests_require=['nose'],
      scripts=['bin/script-command_line'],
      include_package_data=True,
      zip_safe=False)

